#!/usr/bin/env python
# encoding: utf-8

"""
Please, mind the order in this list.
"""

REG_KEYS = [{"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Internet Settings",
             "values": ["ProxyEnable", "AutoConfigURL", "ProxyOverride", "ProxyServer"]},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Internet Explorer\Main",
             "values": ["Search Page", "Default_Page_URL", "Default_Search_URL", "SearchAssistant", "Local Page", "Start Page"]},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Internet Explorer\Main",
             "values": ["Search Page", "Start Page", "Default_Search_URL", "Local Page"]},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Internet Explorer\Search",
             "values": ["CustomizeSearch", "CustomSearch", "Default_Search_URL", "SearchAssistant"]},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Internet Explorer\Search",
             "values": ["Default_Search_URL", "SearchAssistant"]},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Internet Explorer\URLSearchHooks",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "Software\Microsoft\Internet Explorer\URLSearchHooks",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon",
             "values": ["Shell", "Userinit"]},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows NT\CurrentVersion\Windows",
             "values": ["Run", "Load"]},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Run",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
             "values": []},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunOnce",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce",
             "values": []},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunServices",
            "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices",
             "values": []},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunServicesOnce",
            "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunServicesOnce",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnceEx",
             "values": []},
            {"key": "Startups",
             "subkey": "",
             "values": []},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Policies\Microsoft\Internet Explorer\Control Panel",
             "values": []},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Policies\System",
             "values": ["DisableRegistryTools", "DisableTaskMgr"]},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "values": ["DisableRegistryTools", "DisableTaskMgr"]},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run",
             "values": []},
            {"key": "winlogon",
             "subkey": "",
             "values": []},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows",
             "values": ["AppInit_DLLs"]},
            ]
