#!/usr/bin/env python
# encoding: utf-8

"""
Please, mind the order in this list.
"""

REG_KEYS = [{"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Internet Settings",
             "values": ["ProxyEnable", "AutoConfigURL", "ProxyOverride", "ProxyServer"],
             "tag": "IE - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Internet Explorer\Main",
             "values": ["Search Page", "Default_Page_URL", "Default_Search_URL", "SearchAssistant", "Local Page", "Start Page"],
             "tag": "IE - HKLM\..\\"},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Internet Explorer\Main",
             "values": ["Search Page", "Default_Search_URL", "Local Page", "Start Page"],
             "tag": "IE - HKCU\..\\"},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Internet Explorer\Search",
             "values": ["CustomizeSearch", "CustomSearch", "Default_Search_URL", "SearchAssistant"],
             "tag": "IE - HKLM\..\\"},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Internet Explorer\Search",
             "values": ["Default_Search_URL", "SearchAssistant"],
             "tag": "IE - HKCU\..\\"},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Internet Explorer\URLSearchHooks",
             "values": [],
             "tag": "IE - HKCU\..\\"},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "Software\Microsoft\Internet Explorer\URLSearchHooks",
             "values": [],
             "tag": "IE - HKLM\..\\"},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon",
             "values": ["Shell", "Userinit"],
             "tag": "Winlogon - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows NT\CurrentVersion\Windows",
             "values": ["Run", "Load"],
             "tag": "Windows - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Run",
             "values": [],
             "tag": "HKCU\..\Run - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\Run",
             "values": [],
             "tag": "HKLM\..\Run - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunOnce",
             "values": [],
             "tag": "HKCU\..\RunOnce - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce",
             "values": [],
             "tag": "HKLM\..\RunOnce - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunServices",
             "values": [] ,
             "tag": "HKCU\..\RunServices - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices",
             "values": [],
             "tag": "HKLM\..\RunServices - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunServicesOnce",
             "values": [] ,
             "tag": "HKCU\..\RunServicesOnce - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\RunServicesOnce",
             "values": [],
             "tag": "HKLM\..\RunServicesOnce - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnceEx",
             "values": [],
             "tag": "HKLM\..\RunOnceEx - "},
            {"key": "Startups",
             "subkey": "",
             "values": [],
             "tag": ""},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Policies\Microsoft\Internet Explorer\Control Panel",
             "values": [],
             "tag": "IE - Control Panel\\"},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Policies\System",
             "values": ["DisableRegistryTools", "DisableTaskMgr"],
             "tag": "HKCU\..\\"},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System",
             "values": ["DisableRegistryTools", "DisableTaskMgr"],
             "tag": "HKLM\..\Policies\System - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run",
             "values": [],
             "tag": "HKCU\..\Policies\Explorer\Run - "},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run",
             "values": [],
             "tag": "HKLM\..\Policies\Explorer\Run - "},
            {"key": "winlogon",
             "subkey": "",
             "values": [],
             "tag": ""},
            {"key": "HKEY_LOCAL_MACHINE",
             "subkey": "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Windows",
             "values": ["AppInit_DLLs"],
             "tag": "AppInitDLL - "},
            {"key": "HKEY_CURRENT_USER",
             "subkey": "Control Panel\Desktop\MultiUILanguageId",
             "values": [],
             "tag": ""},
            ]
